### ISSUE TITLE
AttributeError: 'gi.repository.Gtk' object has no attribute 'main_quit'

### ISSUE THREAD

**Issue by Flimm** [xenomachina/recently_used#1]
When running this script on Ubuntu 22.04, I get this error:

```
/home/flimm/.local/bin/recently_used.py:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
Adding 'file:///home/flimm/dotfiles/README.md'
Traceback (most recent call last):
  File "/home/flimm/.local/bin/recently_used.py", line 78, in <module>
    main(argparser.parse_args())
  File "/home/flimm/.local/bin/recently_used.py", line 70, in main
    GLib.idle_add(Gtk.main_quit)
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'main_quit'
```

To fix it, I added this line at the top of the script:

```python
import gi
gi.require_version('Gtk', '3.0')
```

**Comment by xenomachina** [comment]
Thanks for the bug report!
